// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace OpenProfilerUI
{
	public partial class AndroidViewController : NSViewController
	{
		public AndroidViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
