// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace OpenProfilerUI
{
    public partial class HomeViewController : NSViewController
    {
        public HomeViewController(IntPtr handle) : base(handle)
        {
        }

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();
            Title = "Launch Profiler";
        }

        public override void ViewDidDisappear()
        {
            base.ViewDidDisappear();
            NSApplication.SharedApplication.Terminate(this);
        }
    }
}
