// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace OpenProfilerUI
{
    public partial class HomeViewController : NSViewController
    {
        public HomeViewController(IntPtr handle) : base(handle)
        {
        }

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();
            Title = "Launch Profiler";
        }

        public override void ViewWillAppear()
        {
            base.ViewWillAppear();
            View.Window.WillClose += OnWindowClose;
        }

        public override void ViewDidDisappear()
        {
            View.Window.WillClose -= OnWindowClose;
            base.ViewDidDisappear();
        }

        private void OnWindowClose(object sender, EventArgs e)
        {
            NSApplication.SharedApplication.Terminate(this);
        }
    }
}
